function Level (sprite)
{
	"use strict";
	this.Sprite = sprite;
	this.DistantBackgroundsSprites = [];
	this.PickableObjects = [
				{
                 "height":72,
                 "id":75,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":843,
                 "y":751
                }, 
                {
                 "height":72,
                 "id":77,
                 "name":"ETERNAL_FLY",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1592,
                 "y":185
                }, 
                {
                 "height":72,
                 "id":78,
                 "name":"SHIELD",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1283,
                 "y":355
                }, 
                {
                 "height":72,
                 "id":79,
                 "name":"PUNCH_SPEED",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":779,
                 "y":208
                }, 
                {
                 "height":72,
                 "id":95,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":341,
                 "y":435
                }, 
                {
                 "height":72,
                 "id":96,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":46,
                 "y":361
                }, 
                {
                 "height":72,
                 "id":97,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":524,
                 "y":890
                }, 
                {
                 "height":72,
                 "id":98,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1060,
                 "y":800
                }, 
                {
                 "height":72,
                 "id":99,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1610,
                 "y":624
                }, 
                {
                 "height":72,
                 "id":100,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1358,
                 "y":779
                }, 
                {
                 "height":72,
                 "id":102,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1608,
                 "y":371
                }, 
                {
                 "height":72,
                 "id":103,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1075,
                 "y":351
                }, 
                {
                 "height":72,
                 "id":104,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":53,
                 "y":899
                }, 
                {
                 "height":72,
                 "id":111,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2219,
                 "y":833.333333333333
                }, 
                {
                 "height":72,
                 "id":112,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2460.33333333333,
                 "y":674.666666666667
                }, 
                {
                 "height":72,
                 "id":113,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2504.33333333333,
                 "y":500
                }, 
                {
                 "height":72,
                 "id":114,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2709.66666666667,
                 "y":861.333333333333
                }, 
                {
                 "height":72,
                 "id":115,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3020.33333333333,
                 "y":889.333333333333
                }, 
                {
                 "height":72,
                 "id":116,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3224.33333333333,
                 "y":624
                }, 
                {
                 "height":72,
                 "id":117,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2908.33333333333,
                 "y":502.666666666667
                }, 
                {
                 "height":72,
                 "id":118,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3929.66666666667,
                 "y":713.333333333333
                }, 
                {
                 "height":72,
                 "id":119,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":4007,
                 "y":908
                }, 
                {
                 "height":72,
                 "id":120,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3549.66666666667,
                 "y":912
                }, 
                {
                 "height":72,
                 "id":121,
                 "name":"PEARL",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3611,
                 "y":689.333333333333
                }, 
                {
                 "height":72,
                 "id":155,
                 "name":"SHIELD",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2699,
                 "y":576
                }, 
                {
                 "height":72,
                 "id":156,
                 "name":"SHIELD",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3813.66666666667,
                 "y":756
                }];
	this.Player = 
				{
                 "height":72,
                 "id":72,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":178,
                 "y":867
                }
	this.Enemys = [
                {
                 "height":72,
                 "id":82,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1603,
                 "y":898
                }, 
                {
                 "height":72,
                 "id":83,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":1383,
                 "y":485
                }, 
                {
                 "height":72,
                 "id":84,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":520,
                 "y":142
                }, 
                {
                 "height":72,
                 "id":86,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":688,
                 "y":847
                }, 
                {
                 "height":72,
                 "id":87,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":720,
                 "y":521
                }, 
                {
                 "height":72,
                 "id":147,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2698,
                 "y":568
                }, 
                {
                 "height":72,
                 "id":148,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":2451,
                 "y":809
                }, 
                {
                 "height":72,
                 "id":149,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3369,
                 "y":905
                }, 
                {
                 "height":72,
                 "id":150,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3942,
                 "y":903
                }, 
                {
                 "height":72,
                 "id":151,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3634,
                 "y":663
                }, 
                {
                 "height":72,
                 "id":152,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3766,
                 "y":901
                }, 
                {
                 "height":72,
                 "id":153,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":74,
                 "x":3957,
                 "y":721
                }];
	this.Platforms = [
                {
                 "height":13,
                 "id":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":443,
                 "x":2,
                 "y":987
                }, 
                {
                 "height":16,
                 "id":4,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":42,
                 "x":483,
                 "y":979
                }, 
                {
                 "height":13,
                 "id":5,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":75,
                 "x":529,
                 "y":985
                }, 
                {
                 "height":14,
                 "id":7,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":33,
                 "x":606,
                 "y":978
                }, 
                {
                 "height":12,
                 "id":8,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":39,
                 "x":630,
                 "y":970
                }, 
                {
                 "height":13,
                 "id":9,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":37,
                 "x":647,
                 "y":960
                }, 
                {
                 "height":12,
                 "id":10,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":43,
                 "x":662,
                 "y":950
                }, 
                {
                 "height":14,
                 "id":11,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":83,
                 "x":683,
                 "y":941
                }, 
                {
                 "height":18,
                 "id":12,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":27,
                 "x":757,
                 "y":949
                }, 
                {
                 "height":17,
                 "id":13,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":775,
                 "y":956
                }, 
                {
                 "height":20,
                 "id":14,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":24,
                 "x":801,
                 "y":965
                }, 
                {
                 "height":15,
                 "id":15,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":40,
                 "x":813,
                 "y":977
                }, 
                {
                 "height":14,
                 "id":16,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":125,
                 "x":848,
                 "y":983
                }, 
                {
                 "height":13,
                 "id":17,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":35,
                 "x":881,
                 "y":944
                }, 
                {
                 "height":13,
                 "id":18,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":195,
                 "x":997,
                 "y":915
                }, 
                {
                 "height":12,
                 "id":19,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":165,
                 "x":1014,
                 "y":903
                }, 
                {
                 "height":13,
                 "id":20,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":119,
                 "x":1030,
                 "y":893
                }, 
                {
                 "height":12,
                 "id":21,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":71,
                 "x":843,
                 "y":836
                }, 
                {
                 "height":13,
                 "id":22,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":61,
                 "x":704,
                 "y":753
                }, 
                {
                 "height":12,
                 "id":23,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":121,
                 "x":702,
                 "y":674
                }, 
                {
                 "height":14,
                 "id":24,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":80,
                 "x":715,
                 "y":617
                }, 
                {
                 "height":13,
                 "id":25,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":80,
                 "x":199,
                 "y":737
                }, 
                {
                 "height":9,
                 "id":26,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":82,
                 "x":342,
                 "y":675
                }, 
                {
                 "height":17,
                 "id":27,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":77,
                 "x":505,
                 "y":623
                }, 
                {
                 "height":14,
                 "id":28,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":116,
                 "x":323,
                 "y":528
                }, 
                {
                 "height":12.6667,
                 "id":30,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":43.3333,
                 "x":191.333,
                 "y":611.333
                }, 
                {
                 "height":10,
                 "id":31,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":28,
                 "x":165.333,
                 "y":615.333
                }, 
                {
                 "height":14,
                 "id":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":60,
                 "x":48.6667,
                 "y":606
                }, 
                {
                 "height":13.3333,
                 "id":33,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":36,
                 "x":96,
                 "y":598
                }, 
                {
                 "height":10.6667,
                 "id":34,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32.6667,
                 "x":124,
                 "y":605.333
                }, 
                {
                 "height":12.6667,
                 "id":35,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":21.3333,
                 "x":147.333,
                 "y":610
                }, 
                {
                 "height":11.3333,
                 "id":36,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":22.6667,
                 "x":82,
                 "y":601.333
                }, 
                {
                 "height":12.6667,
                 "id":37,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":65.3333,
                 "x":48.6667,
                 "y":460
                }, 
                {
                 "height":13.3333,
                 "id":39,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":121.333,
                 "x":496.667,
                 "y":228
                }, 
                {
                 "height":15,
                 "id":40,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":121,
                 "x":753,
                 "y":307
                }, 
                {
                 "height":14,
                 "id":41,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":68,
                 "x":992,
                 "y":295
                }, 
                {
                 "height":16,
                 "id":42,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":50,
                 "x":992,
                 "y":443
                }, 
                {
                 "height":13,
                 "id":43,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":39,
                 "x":1138,
                 "y":446
                }, 
                {
                 "height":12,
                 "id":44,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":34,
                 "x":1109,
                 "y":454
                }, 
                {
                 "height":14,
                 "id":45,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":46,
                 "x":1033,
                 "y":436
                }, 
                {
                 "height":10,
                 "id":46,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":27,
                 "x":1074,
                 "y":444
                }, 
                {
                 "height":14,
                 "id":47,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":21,
                 "x":1095,
                 "y":450
                }, 
                {
                 "height":12,
                 "id":48,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":1281,
                 "y":459
                }, 
                {
                 "height":13,
                 "id":49,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":52,
                 "x":1280,
                 "y":606
                }, 
                {
                 "height":17,
                 "id":50,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1313,
                 "y":595
                }, 
                {
                 "height":15,
                 "id":51,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":33,
                 "x":1340,
                 "y":597
                }, 
                {
                 "height":15,
                 "id":52,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":37,
                 "x":1365,
                 "y":604
                }, 
                {
                 "height":15,
                 "id":53,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":35,
                 "x":1397,
                 "y":614
                }, 
                {
                 "height":16,
                 "id":54,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":42,
                 "x":1424,
                 "y":604
                }, 
                {
                 "height":10,
                 "id":56,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":122,
                 "x":1570,
                 "y":262
                }, 
                {
                 "height":14,
                 "id":60,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":124,
                 "x":1569,
                 "y":450
                }, 
                {
                 "height":12,
                 "id":62,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":124,
                 "x":1567,
                 "y":550
                }, 
                {
                 "height":17,
                 "id":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":122,
                 "x":1585,
                 "y":707
                }, 
                {
                 "height":14,
                 "id":65,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":121,
                 "x":1777,
                 "y":746
                }, 
                {
                 "height":12,
                 "id":66,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":121,
                 "x":1601,
                 "y":836
                }, 
                {
                 "height":11,
                 "id":67,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":47,
                 "x":1265,
                 "y":881
                }, 
                {
                 "height":15,
                 "id":68,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":46,
                 "x":1486,
                 "y":895
                }, 
                {
                 "height":13,
                 "id":70,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":90,
                 "x":1349,
                 "y":873
                }, 
                {
                 "height":17,
                 "id":71,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":847,
                 "x":1199,
                 "y":991
                }, 
                {
                 "height":15,
                 "id":88,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":113,
                 "x":1573,
                 "y":163
                }, 
                {
                 "height":9,
                 "id":92,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":190,
                 "x":486,
                 "y":985
                }, 
                {
                 "height":20,
                 "id":93,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":62,
                 "x":784,
                 "y":978
                }, 
                {
                 "height":18,
                 "id":94,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":148,
                 "x":663,
                 "y":970
                }, 
                {
                 "height":16,
                 "id":109,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":776.667,
                 "x":3314.67,
                 "y":995.333
                }, 
                {
                 "height":14,
                 "id":122,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":67,
                 "x":2224,
                 "y":922
                }, 
                {
                 "height":16,
                 "id":123,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":2448,
                 "y":896
                }, 
                {
                 "height":16,
                 "id":124,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":120,
                 "x":2445,
                 "y":813
                }, 
                {
                 "height":16,
                 "id":125,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":83,
                 "x":2458,
                 "y":760
                }, 
                {
                 "height":17,
                 "id":126,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":119,
                 "x":2481,
                 "y":590
                }, 
                {
                 "height":21,
                 "id":127,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":81,
                 "x":2695,
                 "y":674
                }, 
                {
                 "height":16,
                 "id":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":78,
                 "x":2704,
                 "y":967
                }, 
                {
                 "height":13,
                 "id":129,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":57,
                 "x":2727,
                 "y":960
                }, 
                {
                 "height":13,
                 "id":130,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":43,
                 "x":2743,
                 "y":952
                }, 
                {
                 "height":17,
                 "id":131,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":42,
                 "x":2635,
                 "y":1003
                }, 
                {
                 "height":17,
                 "id":132,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":83,
                 "x":2051,
                 "y":994
                }, 
                {
                 "height":15,
                 "id":134,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":69,
                 "x":2050,
                 "y":981
                }, 
                {
                 "height":10,
                 "id":135,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":42,
                 "x":2062,
                 "y":974
                }, 
                {
                 "height":14,
                 "id":136,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":79,
                 "x":3015,
                 "y":979
                }, 
                {
                 "height":15,
                 "id":138,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":67,
                 "x":3231,
                 "y":714
                }, 
                {
                 "height":16,
                 "id":139,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":122,
                 "x":2881,
                 "y":588
                }, 
                {
                 "height":20,
                 "id":140,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":121,
                 "x":3586,
                 "y":780
                }, 
                {
                 "height":19,
                 "id":141,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":52,
                 "x":3858,
                 "y":843
                }, 
                {
                 "height":19,
                 "id":142,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":49,
                 "x":3899,
                 "y":824
                }, 
                {
                 "height":21,
                 "id":143,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":110,
                 "x":3940,
                 "y":811
                }, 
                {
                 "height":12,
                 "id":157,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":80,
                 "x":1751,
                 "y":353
                }];
    this.WinRect = 
				{
                 "height":51.33,
                 "id":159,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":37.67,
                 "x":3813.67,
                 "y":941.67
                }
}